name: CI

on:
  pull_request:
  schedule:
    # NOTE: We run this weekly at 1 am UTC on every Saturday
    - cron:  '0 1 * * 6'

jobs:
  # This is mirrored in the release workflow.
  build_and_test:
    name: 'Build and Test'
    uses: StackStorm-Exchange/ci/.github/workflows/pack-build_and_test.yaml@59a61ac0b69c6bf9ea57715f566198de49fe4443 # master
    with:
      enable-common-libs: true
      #apt-cache-version: v0
      #py-cache-version: v0
      python-version: '["3.10", "3.11"]'
      st2-branch: 15e45d07d1b3a2b5330ef07a47dc258e2d56ded0 # v3.9.0
